---

apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  namespace: dev
spec:
  containers:
    - name: cont1
      image: nginx
      ports: 
      - containerPort: 80
      resources:
        requests:
          memory: "50Mi"
          cpu: "50m" 
        limits:
          memory: "100Mi"
          cpu: "100m"     
