---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq
  namespace: dev
spec:
  hard: 
    limits.cpu: "400m"
    requests.cpu: "200m"
    limits.memory: "100Mi"
    requests.memory: "50Mi"  
