apiVersion: v1
kind: Pod
metadata: 
  name: file4
spec:
  containers:
    - name: cont4
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: cm3  
