---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-1
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      name: mytemplate
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80    
